---
title: "R Notebook"
output: html_notebook
---


```{r}
library(ggplot2)
library(fmsb)
library(plotly)
library(tidyverse)
```


```{r}
data <- as.data.frame(matrix( sample( 2:20 , 10 , replace=T) , ncol=10))
colnames(data) <- c("math" , "english" , "biology" , "music" , "R-coding", "data-viz" , "french" , "physic", "statistic", "sport" )


data <- rbind(rep(20,10) , rep(0,10) , data)

p <- radarchart(data)
```






```{r}
#

champions <- as.data.frame(matrix( c(9,15,4,17,
                                20,13,10,6,
                                1,6,18,5,
                                8,10,13,15,
                                12,9,7,12) #sample( 0:20 , 20 , replace=F)
                              , ncol=5))

colnames(champions) <- c("baking" , "jousting" , "birdwatching" , "stonemasonry" , "snake charming" )

names <- tibble(name = c("Glimbus", "Dorply-Lwyd", "Ghengis", "Shmebuloc"))
  
named <- names %>% 
  bind_cols(champions)



#rownames(data) <- paste(c("a","b","x"))

champions <- rbind(rep(20,5) , rep(0,5) , named)


colors_border=c( rgb(0.2,0.5,0.5,0.9), rgb(0.8,0.2,0.5,0.9) , rgb(0.7,0.5,0.1,0.9) )
colors_in=c( rgb(0.2,0.5,0.5,0.4), rgb(0.8,0.2,0.5,0.4) , rgb(0.7,0.5,0.1,0.4) )


champions %>% 
  filter(name %in% c("0","20","Glimbus")) %>% 
  select(2:6) %>% 
  radarchart(axistype=1 , 
             pcol =colors_border , pfcol=colors_in , plwd=4 , plty=1,
             cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,20,5), cglwd=0.8,
             vlcex=0.8 
  )
```

```{r}

champions <- as.data.frame(matrix( c(9,15,4,17,
                                20,13,10,6,
                                1,6,18,5,
                                8,10,13,15,
                                12,9,7,12) #sample( 0:20 , 20 , replace=F)
                              , ncol=5))

colnames(champions) <- c("baking" , "jousting" , "birdwatching" , "stonemasonry" , "snake charming" )

names <- tibble(name = c("Glimbus", "Dorply-Lwyd", "Ghengis", "Shmebuloc"))
  
named <- names %>% 
  bind_cols(champions)



#rownames(data) <- paste(c("a","b","x"))

champions <- rbind(rep(20,5) , rep(0,5) , named)

write_csv(champions, "champions.csv")
```

