---
title: "R Notebook"
output: html_notebook
---

```{r}
head(drinks_content)
view(drinks_content)
```

```{r}
drinks_content %>% 
  select(Beverage_category, Beverage, Beverage_prep, Calories) %>% 
  filter(!is.na(Calories))

## forgot is.na() must be used within a function

```

```{r}
drinks_content %>% 
  mutate(calorie_difference = Calories - 135, .after = Calories) %>% 
  arrange(Calories)
```

```{r}
Bev <- group_by(drinks_content, Beverage_category)
Bev_Means <- summarise(Bevy, Caloric_avg = mean(Calories))
arrange(Bev_Means, Caloric_avg)[1:3,]
arrange(Bev_Means, Caloric_avg)[(nrow(Bev_Means)-2):nrow(Bev_Means),]

# Signature Esspresso Drinks, frappucinos and smoothies all have a huge average caloric intake of 250 or over, whereas shaken iced beverages and classic espressos are around the 120 mark. Regular coffee has barely any caloric value at all at 4.25ckal

```

```{r}
drinks_content %>% 
  group_by(Beverage_prep) %>% 
  summarise(mean(Calories)) #-> blorb

```

```{r}
mean_cal <- mean(drinks_content$Calories)

drinks_content %>% 
  group_by(Beverage_prep) %>% 
  summarise(mean(Calories)) -> mean_calories_by_prep

residual_ <- mutate(mean_calories_by_prep,
                    caloric_resid = mean(Calories) - mean_cal > 0,
                    .after = Calories)

filter(residual_, caloric_resid == TRUE)
#select(residual_,1:3, caloric_resid)


```

