---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
view(backpack)
```



2. Distribution of weights

```{r}
ggplot(backpack) +
  aes(backpack_weight) +
  geom_histogram(binwidth = 1)
```


3.

AAAAAAAAAA 

NEED TO DECOUPLE SEX

```{r}
ggplot(backpack) +
  aes(backpack_weight, fill = sex) +
  geom_bar(postition = "dodge")
```

4. BODYWEIGHT AND BACKPACK

```{r}
ggplot(backpack) +
  aes(body_weight, backpack_weight) +
  geom_point() +
  geom_smooth(model = "lm")
```



5. 

```{r}
ggplot(backpack) +
  aes(body_weight, backpack_weight, colour = sex) +
  geom_point() +
  geom_smooth(method = "lm", se = F, size = 2, alpha = 0.3)
```

ALPHA NOT WORKING


6. proportion of back pain

```{r}
pain <- backpack %>% 
  count(back_problems)

#pain$n[2]/sum(pain$n)

ggplot(pain, aes(x="", y=n, fill = as.factor(back_problems))) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start=0) +
  theme_void() +
 # scale_fill_manual(breaks = 0:1, values = c("grey40", "red"), guide = "none") +
  geom_text(aes(label = paste0(n, "%")), position = position_stack(vjust=0.5)) +
  labs(
    title = "Back Pain"
  )
```



```{r}
backpack %>% 
  mutate(bp_fact = as.factor(back_problems)) %>% 

ggplot() +
  aes(back_problems, fill = sex) +
  geom_bar(position = "dodge") 
  
```

HUGE PROBLEM: KEEPS READING DISCREET VARIABLES AS CONTINUOUS

8.

```{r}
ggplot(backpack) +
  aes(sex, ratio, fill = sex, colour = "") +
  geom_boxplot() +
  facet_wrap(~ back_problems)
```

